### ISSUE TITLE
Create getting started tutorial

### ISSUE THREAD

**Issue by andpodob** [membraneframework/membrane_tutorials#3]
I expect this tutorial will be the place where readers will be able to get a good understanding of:
- differences in API and implementation implications of those differences in different types of elements (sink, source, filter),
- push/pull modes, handling demands, etc.,
- defining pads, their options, and caps (it should particularly mention RemoteStream caps as this is a concept that sometimes is not clear to experienced Membrane developers),
- defining options of the element and retrieving them in handle_init,
- introduce the concept of the Pipeline and Bin
 It would be great to wrap all this into some story of creating a pipeline of the custom elements, but elements with really simple logic. Maybe pipeline where source generates some random numbers, the first filter drops all buffers that contain even numbers, second dispatches numbers by looking what is their remainder or sth like that.

**Comment by varsill** [comment]
As discussed, the pipeline could be something like that:
1. We have an input file which consists, for instance, of 100 lines from some kind of a book. Each line number could be considered a timestamp.
2. We want to simulate a situation, in which we would need to gather the lines of the book sent from two different sources into one file which would be written to the storage (the user could then easily check that if the pipeline works as expected since the output file should be the same as the input file)
3. The following elements would be used in the pipeline:
  a. Source (A, B) - on demand, it would read a randomly chosen line from the input file the lines in the range [A, B]. It would simulate the situation in which we would have an unreliable connection and could be sure whether the packets won't get retransmitted or be delivered in the order different than the timestamp-based oder.
  b. Filter1 would read the lines sent by Source and collect them in the order based on their segment id (which would be revenant to the range of the lines from which the given Source reads). It would also drop the duplicated lines.
  c. Filter2 would read the lines ordered by the segment_id sent from two Filter1 elements. Its responsibility would be to put it in order basing on the content of the lines (to be precise - on a timestamp - which is a line number). Filter2 would hold an array (a buffer of a given size) which initially would be empty. Once the new line would be received it would try to place it somewhere in the array. In case there would be a consistent part of the bottom part of the array available (on the bottom means - with the lowest timestamp), it would send such a consistent fragment to the Sink.
  d. Sink - it would read the fragments sent by Filter2 and write them to the file. Since Filter2 would sent fragments which would be sorted by timestamp, consistent and the fragments would also be sent as ordered by the timestamps of the lines they contain, the Source could easily open the file once and append the lines to the file (without performing any 'jumps' between the lines).
5. The pipeline would be as follows: 
Source ——-—> Filter1 (0 - 70) -----—— Filter 2 ———> Sink
   |									  ^  
   | ——————> Filter1 (30 - 100) ————— |

**Comment by varsill** [comment]
closed by #14
